name: fic_1_dart_basic
description: A sample command-line application.
# version: 3.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.2 <3.0.0'

#dependencies:
#  path: ^2.15.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
